apiVersion: v2
name: deploy
description: A Helm chart for deploying stateless and stateful applications as Deployments or StatefulSets
type: application
version: 2.10.0-dev
appVersion: "latest"
home: https://pfnapp.github.io/charts
maintainers:
  - name: pfnapp-team
keywords:
  - deployment
  - ingress
  - haproxy
  - configmap
  - secret
