{{- $rbacEnabled := (include "deploy.rbacIsEnabled" . | trim) | eq "true" -}}
{{- $createServiceAccount := or .Values.serviceAccount.create (and (not .Values.serviceAccount.name) $rbacEnabled) -}}
{{- if $createServiceAccount -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "deploy.serviceAccountName" . }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if ne .Values.serviceAccount.automountServiceAccountToken nil }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end }}
